### PR TITLE
Add translation

### PR DESCRIPTION
**Pull request by RenaudR**

### CODE REVIEW

**Comment by mitchelldavis44** [comment]
Merged, thanks

**Comment by RenaudR** [comment]
Good evening Mitchell Davis, would it be possible to have your gmail or if you have a Goggle +, I can tell you in my translations?

**Comment by mitchelldavis44** [comment]
Sure, I added you on G+.

**Comment by RenaudR** [comment]
@mitchelldavis44 Thank you I did the same on my side :)

**Pull request closed without merging**
